setwd("C:/Users/danie/OneDrive/Documentos/Daniel/Formación complementaria/Data Analysis/Exploratory Data Analysis/ExData_Plotting1")
archivo<-read.csv(file="household_power_consumption.txt",sep=";")
archivo<-subset(archivo,archivo$Date=="1/2/2007"|archivo$Date=="2/2/2007")
archivo$FullDate<-paste(archivo$Date,archivo$Time)
archivo$FullDate<-strptime(archivo$FullDate,format="%d/%m/%Y %H:%M:%S")
png("plot2.png", width = 480, height = 480)
with(archivo,plot(FullDate,Global_active_power,type="l",lwd=1,ylab="Global Active Power (kilowatts",xlab=""))
legend("topright",legend=c("jue = Thursday","vie = Friday","sáb = Saturday"))
dev.off()
